version: 1.0
title: "演示服务"
description: "用于演示的文档"
contact:
 name: srchen
 email: "suxuan696@gmail.com"
 url: "https://github.com/srchen1987"
swagger: "2.0"
host: "localhost"
basePath: "/"
scanPath:
 - "/home/srchen/github/api-demo"
outPath: "/home/srchen/github/api-demo/demo-api.json"